logging:
  level:
    root: info
  file:
    name: logs/application.log
spring:
  application:
    name: Booking-Room-Service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:booking-room}
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8388